name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
  SERVICE_NAME: ml-pipeline

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pylint black
    
   # - name: Run tests
    #  run: |
     #   python -m pytest tests/ -v
    
    - name: Lint code
      run: |
        python -m black . --check
        python -m pylint api/ app.py

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Update and restart on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/$SERVICE_NAME
          
          # Stop existing services
          sudo systemctl stop ml-api streamlit-app || true
          
          # Simple git update - this won't affect model files since they're not in repo
          echo "Updating repository..."
          git fetch origin
          git reset --hard origin/main
          

          source venv/bin/activate
          
          # Install/update dependencies
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Restart services (assume they exist)
          sudo systemctl restart ml-api streamlit-app nginx
          
          # Health check
          echo "Performing health checks..."
          sleep 10
          curl -f http://localhost:8501 || echo "Streamlit health check failed"
          curl -f http://localhost:8000/docs || echo "API health check failed"
